# Generated by Django 4.2.30 on 2026-04-25 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atelier_erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='atelier_erp.task'),
        ),
    ]
