# Generated by Django 4.2.30 on 2026-04-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atelier_erp', '0002_alter_quote_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Existing order this quote was created for (direct order flow)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_quotes', to='atelier_erp.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_work', 'В работе'), ('in_production', 'В производстве'), ('ready', 'Готов'), ('on_installation', 'На установке / выдаче'), ('waiting_final_payment', 'Ожидает финальной оплаты'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('draft', 'Draft'), ('measurement', 'Measurement Scheduled'), ('design', 'Design in Progress'), ('quoted', 'Quote Generated'), ('approved', 'Approved by Customer'), ('prepayment_received', 'Prepayment Received'), ('fabric_reserved', 'Fabric Reserved'), ('production', 'In Production'), ('installation', 'Installation Scheduled')], db_index=True, default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_work', 'В работе'), ('in_production', 'В производстве'), ('ready', 'Готов'), ('on_installation', 'На установке / выдаче'), ('waiting_final_payment', 'Ожидает финальной оплаты'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('draft', 'Draft'), ('measurement', 'Measurement Scheduled'), ('design', 'Design in Progress'), ('quoted', 'Quote Generated'), ('approved', 'Approved by Customer'), ('prepayment_received', 'Prepayment Received'), ('fabric_reserved', 'Fabric Reserved'), ('production', 'In Production'), ('installation', 'Installation Scheduled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('in_work', 'В работе'), ('in_production', 'В производстве'), ('ready', 'Готов'), ('on_installation', 'На установке / выдаче'), ('waiting_final_payment', 'Ожидает финальной оплаты'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('draft', 'Draft'), ('measurement', 'Measurement Scheduled'), ('design', 'Design in Progress'), ('quoted', 'Quote Generated'), ('approved', 'Approved by Customer'), ('prepayment_received', 'Prepayment Received'), ('fabric_reserved', 'Fabric Reserved'), ('production', 'In Production'), ('installation', 'Installation Scheduled')], max_length=30),
        ),
    ]
