# Generated by Django 4.2.30 on 2026-04-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier_erp', '0003_add_quote_order_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='supply_mode',
            field=models.CharField(choices=[('in_stock', 'На складе'), ('purchase_local', 'Закупить (локально)'), ('purchase_import', 'Закупить (импорт)'), ('client_supplied', 'Клиентский материал')], db_index=True, default='in_stock', help_text='How the fabric/material will be supplied for this item', max_length=20),
        ),
    ]
