# Generated by Django 4.2.30 on 2026-04-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier_erp', '0004_quoteitem_supply_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='material_readiness',
            field=models.CharField(choices=[('not_ready', 'Не обеспечен'), ('partially_ready', 'Частично обеспечен'), ('ready', 'Обеспечен материалами'), ('24', 'Grace Period Hours')], db_index=True, default='not_ready', help_text='Operational state: whether order materials are ready for production', max_length=20),
        ),
    ]
