# Generated by Django 4.2.30 on 2026-04-28 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atelier_erp', '0005_order_material_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, help_text='Reason for order cancellation'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='handover_stage',
            field=models.CharField(choices=[('not_required', 'Не требуется'), ('pending', 'Ожидает установки / выдачи'), ('scheduled', 'Запланировано'), ('in_progress', 'В процессе'), ('done', 'Передано / установлено')], db_index=True, default='not_required', help_text='Handover/installation progress stage', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='production_stage',
            field=models.CharField(choices=[('not_started', 'Не начато'), ('cutting', 'Раскрой'), ('sewing', 'Пошив'), ('quality_check', 'Контроль качества'), ('done', 'Производство завершено')], db_index=True, default='not_started', help_text='Production progress stage', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='material_readiness',
            field=models.CharField(choices=[('not_ready', 'Не обеспечен'), ('partially_ready', 'Частично обеспечен'), ('ready', 'Обеспечен материалами')], db_index=True, default='not_ready', help_text='Operational state: whether order materials are ready for production', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['production_stage', 'status'], name='idx_order_prod_stage'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['handover_stage', 'status'], name='idx_order_handover_stage'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['cancelled_at'], name='idx_order_cancelled_at'),
        ),
    ]
