# Generated by Django 4.2.30 on 2026-05-01 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atelier_erp', '0006_order_cancel_reason_order_cancelled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Photo file (jpg/jpeg/png/webp, max 10MB)', upload_to='photo_reports/%Y/%m/')),
                ('caption', models.TextField(blank=True, help_text='Optional description')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_reports', to='atelier_erp.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_reports', to='atelier_erp.orderitem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photo_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo Report',
                'verbose_name_plural': 'Photo Reports',
                'db_table': 'photo_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'is_active'], name='idx_photoreport_order_active'), models.Index(fields=['created_at'], name='idx_photoreport_created')],
            },
        ),
    ]
