# Generated by Django 4.2.30 on 2026-05-01 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atelier_erp', '0007_photoreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCompletionAct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('act_number', models.CharField(db_index=True, help_text='Unique act number, e.g., АВР-О-2026-014', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('signed', 'Подписан')], db_index=True, default='draft', max_length=20)),
                ('signed_file', models.FileField(blank=True, help_text='Signed act file (PDF, JPG, PNG, WebP, max 20MB)', null=True, upload_to='completion_acts/%Y/%m/')),
                ('signed_at', models.DateTimeField(blank=True, help_text='When the act was signed/uploaded', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the act')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_act', to='atelier_erp.order')),
                ('signed_file_uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_completion_acts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Completion Act',
                'verbose_name_plural': 'Order Completion Acts',
                'db_table': 'order_completion_acts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'is_active'], name='idx_complact_order_active'), models.Index(fields=['act_number'], name='idx_complact_number'), models.Index(fields=['status', 'created_at'], name='idx_complact_status_created')],
            },
        ),
    ]
