# Generated by Django 4.2.30 on 2026-05-03 11:51

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atelier_erp', '0009_add_quote_item_fields_and_order_item_room_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='curtain_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curtain_measurements', to='atelier_erp.fabric'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='curtain_meters',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='measurement',
            name='tulle_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tulle_measurements', to='atelier_erp.fabric'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='tulle_meters',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
    ]
