# Generated by Django 4.2.30 on 2026-06-02 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atelier_erp', '0010_measurement_curtain_fabric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_work', 'В работе'), ('in_production', 'В производстве'), ('ready', 'Готов'), ('on_installation', 'На установке / выдаче'), ('waiting_final_payment', 'Ожидает финальной оплаты'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('draft', '[DEPRECATED] Draft'), ('measurement', '[DEPRECATED] Measurement Scheduled'), ('design', '[DEPRECATED] Design in Progress'), ('quoted', '[DEPRECATED] Quote Generated'), ('approved', '[DEPRECATED] Approved by Customer'), ('prepayment_received', '[DEPRECATED] Prepayment Received'), ('fabric_reserved', '[DEPRECATED] Fabric Reserved'), ('production', '[DEPRECATED] In Production'), ('installation', '[DEPRECATED] Installation Scheduled')], db_index=True, default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_work', 'В работе'), ('in_production', 'В производстве'), ('ready', 'Готов'), ('on_installation', 'На установке / выдаче'), ('waiting_final_payment', 'Ожидает финальной оплаты'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('draft', '[DEPRECATED] Draft'), ('measurement', '[DEPRECATED] Measurement Scheduled'), ('design', '[DEPRECATED] Design in Progress'), ('quoted', '[DEPRECATED] Quote Generated'), ('approved', '[DEPRECATED] Approved by Customer'), ('prepayment_received', '[DEPRECATED] Prepayment Received'), ('fabric_reserved', '[DEPRECATED] Fabric Reserved'), ('production', '[DEPRECATED] In Production'), ('installation', '[DEPRECATED] Installation Scheduled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('in_work', 'В работе'), ('in_production', 'В производстве'), ('ready', 'Готов'), ('on_installation', 'На установке / выдаче'), ('waiting_final_payment', 'Ожидает финальной оплаты'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('draft', '[DEPRECATED] Draft'), ('measurement', '[DEPRECATED] Measurement Scheduled'), ('design', '[DEPRECATED] Design in Progress'), ('quoted', '[DEPRECATED] Quote Generated'), ('approved', '[DEPRECATED] Approved by Customer'), ('prepayment_received', '[DEPRECATED] Prepayment Received'), ('fabric_reserved', '[DEPRECATED] Fabric Reserved'), ('production', '[DEPRECATED] In Production'), ('installation', '[DEPRECATED] Installation Scheduled')], max_length=30),
        ),
        migrations.CreateModel(
            name='OrderMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('material_type', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='м', max_length=20)),
                ('status', models.CharField(choices=[('to_buy', 'Закупить'), ('partial', 'Есть частично'), ('ready', 'Готово')], db_index=True, default='to_buy', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='atelier_erp.order')),
                ('source_quote_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_materials', to='atelier_erp.quoteitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Material',
                'verbose_name_plural': 'Order Materials',
                'db_table': 'order_materials',
                'ordering': ['name'],
            },
        ),
    ]
