# Generated by Django 4.2.30 on 2026-06-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier_erp', '0014_simplify_production_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_work', 'В работе'), ('in_production', 'В производстве'), ('ready', 'Готов'), ('on_installation', 'На установке / выдаче'), ('waiting_final_payment', 'Ожидает финальной оплаты'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], db_index=True, default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_work', 'В работе'), ('in_production', 'В производстве'), ('ready', 'Готов'), ('on_installation', 'На установке / выдаче'), ('waiting_final_payment', 'Ожидает финальной оплаты'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('in_work', 'В работе'), ('in_production', 'В производстве'), ('ready', 'Готов'), ('on_installation', 'На установке / выдаче'), ('waiting_final_payment', 'Ожидает финальной оплаты'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], max_length=30),
        ),
    ]
