# Generated by Django 4.2.30 on 2026-06-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier_erp', '0015_cleanup_order_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionassignment',
            name='complexity',
            field=models.CharField(choices=[('low', 'Простой'), ('medium', 'Средний'), ('high', 'Сложный')], db_index=True, default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='productionassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Назначено'), ('materials_prepared', 'Материалы готовы'), ('cutting', 'Раскрой'), ('sewing', 'Пошив'), ('quality_check', 'Контроль качества'), ('ready', 'Готово'), ('returned', 'Возврат на доработку')], db_index=True, default='assigned', max_length=30),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='new_status',
            field=models.CharField(choices=[('assigned', 'Назначено'), ('materials_prepared', 'Материалы готовы'), ('cutting', 'Раскрой'), ('sewing', 'Пошив'), ('quality_check', 'Контроль качества'), ('ready', 'Готово'), ('returned', 'Возврат на доработку')], max_length=30),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='old_status',
            field=models.CharField(blank=True, choices=[('assigned', 'Назначено'), ('materials_prepared', 'Материалы готовы'), ('cutting', 'Раскрой'), ('sewing', 'Пошив'), ('quality_check', 'Контроль качества'), ('ready', 'Готово'), ('returned', 'Возврат на доработку')], max_length=30),
        ),
    ]
