# Generated by Django 4.2.30 on 2026-06-21 05:19

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atelier_erp', '0020_order_stage_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('fabric', 'Ткань'), ('tulle', 'Тюль'), ('cornice', 'Карниз'), ('accessory', 'Фурнитура'), ('other', 'Прочее')], db_index=True, default='accessory', max_length=20)),
                ('unit', models.CharField(choices=[('m', 'м'), ('pcs', 'шт'), ('pack', 'упак')], default='pcs', max_length=10)),
                ('quantity', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('low_stock_threshold', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Порог «на исходе»: остаток ниже подсвечивается', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('supplier', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='atelier_erp.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'inventory_items',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='idx_invitem_active_cat'), models.Index(fields=['tenant', 'is_active'], name='idx_invitem_tenant')],
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', Decimal('0'))), name='invitem_quantity_non_negative'),
        ),
    ]
