# Generated by Django 4.2.30 on 2026-07-06 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("atelier_erp", "0021_inventoryitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="atelier_erp.tenant",
            ),
        ),
    ]
