# Generated by Django 4.2.30 on 2026-07-08 06:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("atelier_erp", "0022_task_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabric",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="atelier_erp.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="fabric",
            name="hanger_number",
            field=models.CharField(
                db_index=True,
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Hanger number must be alphanumeric uppercase",
                        regex="^[A-Z0-9-]{1,50}$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="fabric",
            constraint=models.UniqueConstraint(
                fields=("tenant", "hanger_number"),
                name="fabric_tenant_hanger_number_unique",
            ),
        ),
    ]
