# Generated by Django 4.2.13 on 2026-07-11 16:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atelier_erp", "0023_fabric_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="curtain_gathering",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("2.2"), max_digits=4
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="tulle_gathering",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("2.0"), max_digits=4
            ),
        ),
    ]
