# Generated by Django 4.2.30 on 2026-07-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atelier_erp", "0024_measurement_curtain_gathering_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="materials_ready",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
