# Generated by Django 4.2.30 on 2026-07-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atelier_erp", "0025_measurement_materials_ready"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="sewing_done",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
