# Generated by Django 4.2.30 on 2026-07-18 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("atelier_erp", "0026_measurement_sewing_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="installation_done",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="photoreport",
            name="measurement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo_reports",
                to="atelier_erp.measurement",
            ),
        ),
    ]
