# Generated by Django 4.2.30 on 2026-07-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atelier_erp", "0027_measurement_installation_done_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
