# Generated by Django 4.2.30 on 2026-07-20 14:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("atelier_erp", "0028_measurement_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="cornice_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cornice_measurements",
                to="atelier_erp.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="cornice_quantity",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="hardware_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hardware_measurements",
                to="atelier_erp.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="hardware_quantity",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=8
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                db_index=True,
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone must be 10-20 digits",
                        regex="^\\+?[\\d\\s()-]{10,20}$",
                    )
                ],
            ),
        ),
    ]
