# Generated by Django 4.2.30 on 2026-07-20 14:36

import re

from django.db import migrations, models
import django.db.models.deletion

_HANGER_INVALID = re.compile(r'[^A-Z0-9-]')


def _sanitize_hanger_number(raw, fallback_id):
    cleaned = _HANGER_INVALID.sub('-', (raw or '').upper()).strip('-')
    if cleaned:
        return cleaned[:50]
    return f"ITM-{str(fallback_id).replace('-', '').upper()[:8]}"


def backfill_fabric_category_and_source_item(apps, schema_editor):
    """
    Проставляет category/source_item на уже существующих Fabric-записях,
    доматчивая их по старому ключу (tenant, hanger_number) — так же, как
    это делает `sync_fabric_from_inventory_item` для легаси-строк без
    source_item. Записи, для которых живой InventoryItem не находится
    (осиротевшие дубликаты от старого бага с hanger_number='MAT'),
    остаются с пустой category — и поэтому перестают попадать в
    отфильтрованные по категории выпадашки на фронте, не будучи удалены.
    """
    Fabric = apps.get_model('atelier_erp', 'Fabric')
    InventoryItem = apps.get_model('atelier_erp', 'InventoryItem')

    for item in InventoryItem.objects.filter(category__in=['fabric', 'tulle']):
        hanger_number = _sanitize_hanger_number(item.sku or item.name, item.id)
        category = 'tulle' if item.category == 'tulle' else 'fabric'
        fabric = Fabric.objects.filter(
            tenant=item.tenant, hanger_number=hanger_number, source_item__isnull=True,
        ).first()
        if fabric is not None:
            fabric.category = category
            fabric.source_item_id = item.id
            fabric.save(update_fields=['category', 'source_item'])


class Migration(migrations.Migration):

    dependencies = [
        ("atelier_erp", "0029_measurement_cornice_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabric",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("fabric", "Ткань"), ("tulle", "Тюль")],
                db_index=True,
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="fabric",
            name="source_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="synced_fabric",
                to="atelier_erp.inventoryitem",
            ),
        ),
        migrations.RunPython(backfill_fabric_category_and_source_item, migrations.RunPython.noop),
    ]
