# Generated by Django 4.2.30 on 2026-07-20 14:49

from django.db import migrations


def backfill_room_window(apps, schema_editor):
    """
    До этой сессии `_create_order_item_from_quote_item` не копировал
    room_name/window_name на OrderItem (оседали только внутри составной
    строки notes) — все ранее сгенерированные позиции остались с пустыми
    полями. Это ломало сопоставление позиции с исходным замером на фронте
    (ItemRow.matchedMeasurement ищет по room_name+window_name).

    Восстанавливаем задним числом ТОЛЬКО однозначные случаи: ищем среди
    QuoteItem'ов заказа (через его КП) единственную строку с теми же
    шириной/высотой окна и той же ценой (unit_price) — если совпадение не
    уникально, пропускаем (осторожность важнее полноты бэкофилла).
    """
    OrderItem = apps.get_model('atelier_erp', 'OrderItem')
    Quote = apps.get_model('atelier_erp', 'Quote')

    broken_items = OrderItem.objects.filter(room_name='', window_name='')
    for item in broken_items.select_related('order'):
        quotes = Quote.objects.filter(order_id=item.order_id)
        candidates = []
        for quote in quotes:
            candidates.extend(
                quote.items.filter(
                    window_width_cm=item.window_width_cm,
                    window_height_cm=item.window_height_cm,
                    line_total=item.unit_price,
                )
            )
        if len(candidates) == 1:
            match = candidates[0]
            item.room_name = match.room_name
            item.window_name = match.window_name
            item.save(update_fields=['room_name', 'window_name'])


class Migration(migrations.Migration):

    dependencies = [
        ("atelier_erp", "0030_fabric_category_fabric_source_item"),
    ]

    operations = [
        migrations.RunPython(backfill_room_window, migrations.RunPython.noop),
    ]
