# Generated by Django 4.2.30 on 2026-07-21 10:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("atelier_erp", "0031_backfill_order_item_room_window"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialDeduction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deductions",
                        to="atelier_erp.inventoryitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_deductions",
                        to="atelier_erp.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Deduction",
                "verbose_name_plural": "Material Deductions",
                "db_table": "material_deductions",
                "indexes": [
                    models.Index(
                        fields=["order", "reversed_at"],
                        name="idx_matded_order_reversed",
                    )
                ],
            },
        ),
    ]
