# Generated by Django 4.2.30 on 2026-07-21 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("atelier_erp", "0032_materialdeduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialdeduction",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="material_deductions",
                to="atelier_erp.orderitem",
            ),
        ),
    ]
