import type { RoleKey, WorkQueueResponse, WorkQueueItem } from '../types/work';

const baseItems: WorkQueueItem[] = [
  {
    id: 'w1',
    orderId: 'demo-1',
    orderNumber: 'З-2026-001',
    clientName: 'Алиева Светлана',
    clientPhone: '+7 701 123 45 67',
    address: 'Алматы, пр. Назарбаева 42, кв. 15',
    status: 'in_work',
    priority: 'high',
    dueDate: '2026-06-15',
    stage: 'measurement',
    materialReadiness: 'partially_ready',
    actions: ['Замер', 'КП'],
  },
  {
    id: 'w2',
    orderId: 'demo-2',
    orderNumber: 'З-2026-002',
    clientName: 'Иванов Пётр',
    clientPhone: '+7 707 987 65 43',
    address: 'Алматы, ул. Абылай хана 10, кв. 3',
    status: 'in_production',
    priority: 'medium',
    dueDate: '2026-06-20',
    stage: 'production',
    materialReadiness: 'ready',
    actions: ['Пошив'],
  },
  {
    id: 'w3',
    orderId: 'demo-3',
    orderNumber: 'З-2026-003',
    clientName: 'Ким Анна',
    clientPhone: '+7 747 555 33 22',
    address: 'Алматы, мкр. Самал, д. 7, кв. 12',
    status: 'installation',
    priority: 'urgent',
    dueDate: '2026-05-28',
    stage: 'installation',
    materialReadiness: 'ready',
    actions: ['Установка', 'Фотоотчёт'],
  },
  {
    id: 'w4',
    orderId: 'demo-4',
    orderNumber: 'З-2026-004',
    clientName: 'Нурбеков Данияр',
    clientPhone: '+7 775 111 22 33',
    address: 'Алматы, пр. Аль-Фараби 77, оф. 405',
    status: 'waiting_final_payment',
    priority: 'low',
    dueDate: '2026-06-01',
    stage: 'payment',
    materialReadiness: 'ready',
    actions: ['АВР', 'Оплата'],
  },
  {
    id: 'w5',
    orderId: 'demo-5',
    orderNumber: 'З-2026-005',
    clientName: 'Бекжанова Гульнар',
    clientPhone: '+7 701 777 88 99',
    address: 'Алматы, ул. Толе би 25, кв. 8',
    status: 'completed',
    priority: 'low',
    dueDate: '2026-05-15',
    stage: 'completed',
    materialReadiness: 'ready',
    actions: ['Архив'],
  },
];

export const DEMO_WORK_QUEUES: Record<RoleKey, WorkQueueResponse> = {
  owner: {
    role: 'owner',
    count: 5,
    items: baseItems,
  },
  designer: {
    role: 'designer',
    count: 2,
    items: baseItems.filter((i) => i.stage === 'measurement'),
  },
  quotes: {
    role: 'quotes',
    count: 1,
    items: baseItems.filter((i) => i.stage === 'measurement').slice(0, 1),
  },
  warehouse: {
    role: 'warehouse',
    count: 2,
    items: baseItems.filter((i) => i.materialReadiness !== 'ready'),
  },
  production: {
    role: 'production',
    count: 2,
    items: baseItems.filter((i) => i.stage === 'production' || i.status === 'in_production'),
  },
  installation: {
    role: 'installation',
    count: 1,
    items: baseItems.filter((i) => i.stage === 'installation'),
  },
  finance: {
    role: 'finance',
    count: 1,
    items: baseItems.filter((i) => i.stage === 'payment'),
  },
};
