import type { RoleKey, WorkQueueResponse, WorkQueueItem } from '../types/work';

/* ─── Дизайнер / Замерщик ─── */
const designerItems: WorkQueueItem[] = [
  {
    id: 'd1',
    orderId: 'demo-d1',
    orderNumber: 'З-2026-011',
    clientName: 'Омарова Айгуль',
    clientPhone: '+7 701 111 22 33',
    address: 'Алматы, мкр. Аксай 12, кв. 45',
    status: 'new',
    priority: 'high',
    dueDate: '2026-06-18',
    stage: 'measurement',
    materialReadiness: 'not_ready',
    actions: ['Нужно сделать замер'],
    context: 'Гостиная, 3 окна → Передать в КП',
  },
  {
    id: 'd2',
    orderId: 'demo-d2',
    orderNumber: 'З-2026-012',
    clientName: 'Сарсенбаев Нурлан',
    clientPhone: '+7 707 222 33 44',
    address: 'Алматы, ул. Жандосова 88, кв. 12',
    status: 'in_work',
    priority: 'medium',
    dueDate: '2026-06-22',
    stage: 'measurement',
    materialReadiness: 'partially_ready',
    actions: ['Подготовить данные'],
    context: 'Спальня, 2 окна → Передать в КП',
  },
];

/* ─── КП ─── */
const quotesItems: WorkQueueItem[] = [
  {
    id: 'q1',
    orderId: 'demo-q1',
    orderNumber: 'З-2026-013',
    clientName: 'Токтарова Жанар',
    clientPhone: '+7 747 333 44 55',
    address: 'Алматы, пр. Райымбека 55, кв. 7',
    status: 'new',
    priority: 'high',
    dueDate: '2026-06-19',
    stage: 'quotes',
    materialReadiness: 'not_ready',
    actions: ['Составить КП'],
    context: 'Ориентир 180 000 ₸ → Согласовать с клиентом',
  },
  {
    id: 'q2',
    orderId: 'demo-q2',
    orderNumber: 'З-2026-014',
    clientName: 'Есимов Бауыржан',
    clientPhone: '+7 775 444 55 66',
    address: 'Алматы, ул. Сейфуллина 101, кв. 33',
    status: 'in_work',
    priority: 'medium',
    dueDate: '2026-06-25',
    stage: 'quotes',
    materialReadiness: 'partially_ready',
    actions: ['Ожидает согласования'],
    context: 'КП 320 000 ₸ → Создать заказ после принятия',
  },
];

/* ─── Склад ─── */
const warehouseItems: WorkQueueItem[] = [
  {
    id: 'wh1',
    orderId: 'demo-wh1',
    orderNumber: 'З-2026-015',
    clientName: 'Жетписова Гульнара',
    clientPhone: '+7 701 555 66 77',
    address: 'Алматы, мкр. Тастак 8, кв. 21',
    status: 'new',
    priority: 'high',
    dueDate: '2026-06-17',
    stage: 'measurement',
    materialReadiness: 'not_ready',
    actions: ['Закупить'],
    context: 'Блэкаут синий — 8 м, Карниз Somfy — 1 шт',
  },
  {
    id: 'wh2',
    orderId: 'demo-wh2',
    orderNumber: 'З-2026-016',
    clientName: 'Сейдалы Ерлан',
    clientPhone: '+7 707 666 77 88',
    address: 'Алматы, пр. Назарбаева 120, кв. 9',
    status: 'in_production',
    priority: 'medium',
    dueDate: '2026-06-21',
    stage: 'production',
    materialReadiness: 'partially_ready',
    actions: ['Нужно сделать'],
    context: 'Велюр серый — 5.2 м (есть), Органза — нет',
  },
  {
    id: 'wh3',
    orderId: 'demo-wh3',
    orderNumber: 'З-2026-017',
    clientName: 'Аубакирова Сандугаш',
    clientPhone: '+7 747 777 88 99',
    address: 'Алматы, ул. Кабанбай батыра 33, кв. 15',
    status: 'in_production',
    priority: 'low',
    dueDate: '2026-06-20',
    stage: 'production',
    materialReadiness: 'ready',
    actions: ['Сделано'],
    context: 'Лён беж — 3.8 м, Карниз 2.8 м — всё готово',
  },
];

/* ─── Пошив ─── */
const productionItems: WorkQueueItem[] = [
  {
    id: 'p1',
    orderId: 'demo-p1',
    orderNumber: 'З-2026-018',
    clientName: 'Тулегенова Маржан',
    clientPhone: '+7 775 888 99 00',
    address: 'Алматы, мкр. Самал 15, кв. 4',
    status: 'in_production',
    priority: 'medium',
    dueDate: '2026-06-23',
    stage: 'production',
    materialReadiness: 'ready',
    actions: ['Раскрой'],
    context: 'Жаккард золотой — 2.5 м, Кабинет → Пошив',
  },
  {
    id: 'p2',
    orderId: 'demo-p2',
    orderNumber: 'З-2026-019',
    clientName: 'Куандыков Ермек',
    clientPhone: '+7 701 999 00 11',
    address: 'Алматы, ул. Байзакова 44, кв. 18',
    status: 'in_production',
    priority: 'urgent',
    dueDate: '2026-06-16',
    stage: 'production',
    materialReadiness: 'ready',
    actions: ['Пошив'],
    context: 'Хлопок мятный — 3 м, Детская, срочно',
  },
];

/* ─── Установка ─── */
const installationItems: WorkQueueItem[] = [
  {
    id: 'i1',
    orderId: 'demo-i1',
    orderNumber: 'З-2026-020',
    clientName: 'Назарбаева Салтанат',
    clientPhone: '+7 707 000 11 22',
    address: 'Алматы, пр. Аль-Фараби 200, кв. 55',
    status: 'ready',
    priority: 'high',
    dueDate: '2026-06-18',
    stage: 'installation',
    materialReadiness: 'ready',
    actions: ['Назначить установку'],
    context: 'Гостиная панорамное, электрокарниз Somfy',
  },
  {
    id: 'i2',
    orderId: 'demo-i2',
    orderNumber: 'З-2026-021',
    clientName: 'Рахимов Данияр',
    clientPhone: '+7 747 111 22 33',
    address: 'Алматы, ул. Достык 77, кв. 30',
    status: 'installation',
    priority: 'medium',
    dueDate: '2026-06-24',
    stage: 'installation',
    materialReadiness: 'ready',
    actions: ['Фотоотчёт / АВР'],
    context: 'Спальня, АВР черновик → Подписать и оплатить',
  },
];

export const DEMO_WORK_QUEUES: Record<RoleKey, WorkQueueResponse> = {
  owner: {
    role: 'owner',
    count: 8,
    items: [
      ...designerItems,
      ...warehouseItems,
      ...productionItems,
      ...installationItems,
    ],
  },
  designer: {
    role: 'designer',
    count: designerItems.length,
    items: designerItems,
  },
  quotes: {
    role: 'quotes',
    count: 0,
    items: [],
  },
  warehouse: {
    role: 'warehouse',
    count: warehouseItems.length,
    items: warehouseItems,
  },
  production: {
    role: 'production',
    count: productionItems.length,
    items: productionItems,
  },
  installation: {
    role: 'installation',
    count: installationItems.length,
    items: installationItems,
  },
  finance: {
    role: 'finance',
    count: 0,
    items: [],
  },
};
